name: Packaging

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Remove excess files
        run: |
          rm -Rdf $GITHUB_WORKSPACE/.git
          rm -Rdf $GITHUB_WORKSPACE/.github
          rm $GITHUB_WORKSPACE/.gitignore

      - name: Install toolkit
        run: pip install splunk-packaging-toolkit

      - name: Generate manifest
        run: |
          cd ..
          mv weblogic-splunk-app RedRiver_WebLogicServer
          slim generate-manifest RedRiver_WebLogicServer -o RedRiver_WebLogicServer/app.manifest
          cat RedRiver_WebLogicServer/app.manifest

      - name: Validate
        run: |
          ls -al
          cd RedRiver_WebLogicServer
          ls -al
          slim validate ./

      - name: Package
        run: |
          cd ..
          slim package -o out RedRiver_WebLogicServer
