name: Packaging

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Remove excess files
        run: |
          rm -Rdf $GITHUB_WORKSPACE/.git
          rm -Rdf $GITHUB_WORKSPACE/.github
          rm $GITHUB_WORKSPACE/.gitignore

      - name: Install toolkit
        run: pip install splunk-packaging-toolkit

      - name: Generate manifest
        run: |
          cd ..
          slim generate-manifest weblogic-splunk-app -o weblogic-splunk-app/app.manifest
          cat weblogic-splunk-app/app.manifest

      - name: Validate
        run: |
          cd weblogic-splunk-app
          slim validate .

      - name: Package
        run: |
          cd ..
          slim package -o out weblogic-splunk-app
