name: Packaging

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Remove excess files
        run: |
          rm -Rdf $GITHUB_WORKSPACE/.git
          rm -Rdf $GITHUB_WORKSPACE/.github
          rm $GITHUB_WORKSPACE/.gitignore

      - name: Install toolkit
        run: pip install splunk-packaging-toolkit

      - name: Generate manifest
        # generates manifest, trims off lines starting with '#', and then adds workload to json
        run: |
          slim generate-manifest $GITHUB_WORKSPACE -o app.manifest
          sed -i '/#/,$d' app.manifest
          cat <<< $(jq '.targetWorkloads |= ["_forwarders"]' app.manifest) > app.manifest
          cat app.manifest

      - name: Validate
        run: |
          slim validate $GITHUB_WORKSPACE

      - name: Package
        run: |
          cd ..
          slim package -o out $GITHUB_WORKSPACE

      - name: Archive package
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: out