name: Packaging

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Remove excess files
        run: |
          rm -Rdf $GITHUB_WORKSPACE/.git
          rm -Rdf $GITHUB_WORKSPACE/.github
          rm $GITHUB_WORKSPACE/.gitignore

      - name: Install toolkit
        run: |
          pip install splunk-packaging-toolkit
          sudo apt-get install jq

      - name: Generate manifest
        run: |
          slim generate-manifest $GITHUB_WORKSPACE -o app.manifest
          jq '.[0].targetWorkloads |= ["_forwarders"]
          cat app.manifest

      - name: Validate
        run: |
          slim validate $GITHUB_WORKSPACE

      - name: Package
        run: |
          cd ..
          slim package -o ../out $GITHUB_WORKSPACE
