# This is a basic workflow to help you get started with Actions

name: Splunk AppInspect

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: install deps for appinspect
        run: |
          sudo apt-get update
          sudo apt install -y libxml2-dev libxslt-dev lib32z1-dev python-lxml

      - name: update pip and pip setup
        run: |
          sudo pip3 install --upgrade pip
          sudo pip3 install --upgrade pip setuptools

      # Downloads, installs, and runs appinspect
      - name: splunk-appinspect
        run: |
          wget --output-document splunk-appinspect.tar.gz https://download.splunk.com/misc/appinspect/splunk-appinspect-latest.tar.gz
          sudo pip3 install wheel
          sudo pip3 install --ignore-installed PyYAML
          sudo pip3 install splunk-appinspect.tar.gz
          splunk-appinsppect inspect $GITHUB_WORKSPACE --mode precert
